### ISSUE TITLE
What game other than CartPole-v0 is the A2C agent good at?

### ISSUE THREAD

**Issue by wooloo1121** [facebookresearch/salina#40]
Hi,

I've been working with the a2c example agent you provide, and haven't found any game other than CartPole-v0 that it can learn well. Is there any other game that it is good at?

Thank you so much.

Best,
Karin

**Comment by ludc** [comment]
Hi, you can try lunarlander for instance. But the hyper-parameters will have to be correctly tuned. In one of our paper, we are using it for ProcGen also.

 Keep me in touch

 Ludovic

**Comment by wooloo1121** [comment]
Hi Ludovic,

Thank you so much for your quick reply. Can you also show me which parameters to tune and how to tune them for lunarlander? Thank you very much again!

Best,
Karin

**Comment by wooloo1121** [comment]
Hi,

I wonder if the Pong example under a2c complete folder works? It seems I need to change the data type of variable "input" (in A2CAtariAgent) to float for it to run, and it still has a value error after running for a short period of time. Thank you very much.

Best,
Karin
