### ISSUE TITLE
Where can I get the test configuration of the subspace_of_polices example?

### ISSUE THREAD

**Issue by aithlab** [facebookresearch/salina#45]
Hi,

Thanks for sharing your interesting project!
I recently have been interested in the project related to the paper, Learning a Subspace of Policies for Online Adaptation in RL.
In the paper, they commented the code is released in this repository, and I tried to run the code, subspace_of_policies.
I succeeded in running the training code, train.py, after slightly modifying it.
Also, after relatively much modifying the evaluation code, I checked the code was working.
However, I think to confirm the contents represented in the paper the evaluation configuration should be given, which has the components such as the torso, thig, shin, foot, gravity, and friction.

I think the test_cfgs is needed.
`from salina_examples.rl.subspace_of_policies.envs import test_cfgs`

Could you share the code?

Best regards,

**Comment by jbgaya** [comment]
Hi @aithlab 

Glad you liked the project and thanks for finding the bug. The test environments are already available in [halfcheetah.py](https://github.com/facebookresearch/salina/blob/main/salina_examples/rl/subspace_of_policies/envs/halfcheetah.py) but there was a typo in [evaluation.py](https://github.com/facebookresearch/salina/blob/main/salina_examples/rl/subspace_of_policies/evaluation.py). Should be working now !

Can you tell what you modified for the training ? Could be interesting to share if you found a bug.

Best

**Comment by aithlab** [comment]
Thanks for the update and your reply!

The training code uploaded in this repository was working well, and I meant that I slightly modified it for personal research.

Best regards,
