### ISSUE TITLE
Noticed issues with salina_cl

### ISSUE THREAD

**Issue by feifeiobama** [facebookresearch/salina#51]
1. `hugefoot` task missing in `scenarios/brax/ant.py`.
2. `alphas_q_update` needs be set near line 97 of `agents/subspace_agents.py`.
3. Learning rate for `optimizer_policy` and `optimizer_q` in `configs/framework/params/algorithm/humanoidhard/hard.yaml` differ from the paper.
4. There may be a missing coefficient 0.5 at line 67 of `algorithms/sac.py`, according to the salina_cl branch.
5. By the way, Table 8-11 and 12-15 in the paper are identical.

**Comment by jbgaya** [comment]
@feifeiobama thanks for pointing this out! This should be resolved by #53 .

**Comment by datake** [comment]
When I try to run the example: python run.py -cn=csp scenario=halfcheetah/forgetting.

There is an error:  
"[Workspace.get_full] unnknown variable '" + var_name + "'"
AssertionError: [Workspace.get_full] unnknown variable 'alphas_q_update'

How to fix it? Thanks.
